### ISSUE TITLE
change `imports` to code snippets

### ISSUE THREAD

**Issue by INeedJobToStartWork** [dominicbirch/bundle-declarations-webpack-plugin#21]
# Hello!
 
There is option to change in ts transpiler to change `import`'s on code snippets?
## Currently
**index.d.ts**
```ts
import { ZodType } from "zod"

ZodType<import("@clack/prompts").MultiSelectOptions<{
		value: unknown;
		label: string;
		hint?: string | undefined;
}
```
## What i want
**index.d.ts**
```ts
type ZodType<T> = {...}
type MultiSelectOptions<T> = {...}

ZodType<MultiSelectOptions<{
		value: unknown;
		label: string;
		hint?: string | undefined;
}
```
## Context
I'm doing my own package which is bundled with webpack and takes only needed code. 
Im using Types to my config type so i want to take only types which i need to not download full package because it's not needed.

## Example
https://www.npmjs.com/package/commitsmile?activeTab=code

**Comment by dominicbirch** [comment]
Hi,

I think this might be one for the library I'm wrapping with this package (`dts-bundle-generator`) if it's a new feature around the bundling itself.  

[libraries.inlinedLibraries](https://github.com/timocov/dts-bundle-generator/blob/master/src/config-file/README.md) 
 from timocov's library might be worth a look?  You should find this is supported already when using this webpack plugin.
