### ISSUE TITLE
how to show only explicitly classes in .d.ts

### ISSUE THREAD

**Issue by shushenghong** [dominicbirch/bundle-declarations-webpack-plugin#28]
i write a library, many inner classes and functions, i only explicitly export few in the entry index.ts, and i only want show this definations in .d.ts, how to?

**Comment by dominicbirch** [comment]
Hi,

Sorry for not replying sooner!

I this case, it probably wouldn't make sense to use this plug in or a bundle to do it as the intention in this case is to combine the exported types by crawling the imports and producing all exports as 1 `. d. ts`.

If your index was only using these classes this would be what you get, and if there's nothing to bundle up you could use `tsc` to emit just the declaration of 1 file.

**Comment by dominicbirch** [comment]
There might also be options of the bundle generator you could take advantage of in order to get a shorter list of exports
